Throw shfmt against bash scripts
Signed-off-by: Knut Ahlers <knut@ahlers.me>

diff --git a/bin/check_config b/bin/check_config
--- a/bin/check_config
+++ b/bin/check_config
@@ -3,46 +3,55 @@ set -euo pipefail
 
 DEBUG=${DEBUG:-false}
 FETCH_INTERVAL=${FETCH_INTERVAL:-3600}
-REPOS=( public secret )
+REPOS=(public secret)
 SSH_KEY=${SSH_KEY:-fafnir}
 
 # Print debug messages if enabled by ${DEBUG}
-function debug {
-  [[ "${DEBUG}" = "false" ]] && return
+function debug() {
+  [[ ${DEBUG} == "false" ]] && return
   echo "$@" >&2
 }
 
-function join_by { local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}"; }
+function join_by() {
+  local d=$1
+  shift
+  echo -n "$1"
+  shift
+  printf "%s" "${@/#/$d}"
+}
 
 # Wrap git to work with git-dir and work-tree being in other locations
-function gwrap {
+function gwrap() {
   hub --git-dir=${HOME}/.cfg/${REPO} --work-tree=${HOME} $@
 }
 
 # Ensure we're connected to network before acting
-if ! ( ping -q -c 1 8.8.8.8 >/dev/null ); then
+if ! (ping -q -c 1 8.8.8.8 >/dev/null); then
   debug "No network connection, not checking"
   exit 0
 fi
 
 STAT_PARM="-c %Y"
-[[ "$(uname -s)" = "Darwin" ]] && STAT_PARM="-f %m"
+[[ "$(uname -s)" == "Darwin" ]] && STAT_PARM="-f %m"
 
 NEED_UPDATE=()
 # Check repos for updates
 for REPO in ${REPOS[@]}; do
   LAST_FETCH=0
   [ -f ~/.cfg/${REPO}/FETCH_HEAD ] && LAST_FETCH=$(stat ${STAT_PARM} ~/.cfg/${REPO}/FETCH_HEAD)
-  if [ $(( $(date +%s) - ${LAST_FETCH} )) -gt ${FETCH_INTERVAL} ] || \
+  if [ $(($(date +%s) - LAST_FETCH)) -gt ${FETCH_INTERVAL} ] ||
     [ $(wc -c ~/.cfg/${REPO}/FETCH_HEAD | cut -d' ' -f1) -eq 0 ]; then
-    vault-sshadd ${SSH_KEY} 2>&1 >/dev/null || { echo "Unable to load key ${SSH_KEY}"; exit 1; }
+    vault-sshadd ${SSH_KEY} 2>&1 >/dev/null || {
+      echo "Unable to load key ${SSH_KEY}"
+      exit 1
+    }
     gwrap fetch -q origin master
   fi
 
   LOCAL=$(gwrap rev-parse HEAD)
   REMOTE=$(gwrap rev-parse FETCH_HEAD)
 
-  if ! [[ "${LOCAL}" = "${REMOTE}" ]]; then
+  if ! [[ ${LOCAL} == "${REMOTE}" ]]; then
     NEED_UPDATE+=("'${REPO}'")
   fi
 done
diff --git a/bin/clean-keys b/bin/clean-keys
--- a/bin/clean-keys
+++ b/bin/clean-keys
@@ -1,16 +1,16 @@
 #!/bin/bash
 # clean_keyring.sh - clean up all the excess keys
- 
+
 # my key should probably be the first secret key listed
 mykey=$(gpg --list-secret-keys | grep '^sec' | cut -c 13-20)
 if [ -z "$mykey" ]; then
-    # exit if no key string
-    echo "Can't get user's key ID"
-    exit 1
+  # exit if no key string
+  echo "Can't get user's key ID"
+  exit 1
 fi
- 
+
 # all of the people who have signed my key
-mysigners=$(gpg --list-sigs $mykey | grep '^sig' | cut -c 14-21 | sort -u) 
+mysigners=$(gpg --list-sigs $mykey | grep '^sig' | cut -c 14-21 | sort -u)
 
 # keep also the keys of persons I'm tracking on keybase.io
 keybase_tracks=""
@@ -18,23 +18,23 @@ for person in $(keybase list-tracking); do
   id=$(keybase id $person 2>&1 | grep "public key fingerprint" | cut -d ':' -f 2 | cut -c 41-50 | sed "s/ //g")
   keybase_tracks="$keybase_tracks $id"
 done
- 
+
 # keep all of the signers, plus my key (if I haven't self-signed)
 keepers=$(echo $mykey $mysigners $keybase_tracks | tr ' ' '\012' | sort -u)
- 
+
 # the keepers list in egrep syntax: ^(key|key|…)
 keepers_egrep=$(echo $keepers | sed 's/^/^(/; s/$/)/; s/ /|/g;')
- 
+
 # show all the keepers as a comment so this script's output is shell-able
 echo '# Keepers: ' $keepers
- 
+
 # everyone who isn't on the keepers list is deleted
-deleters=$(gpg --list-keys | grep '^pub'|  cut -c 13-20 | egrep -v ${keepers_egrep})
- 
+deleters=$(gpg --list-keys | grep '^pub' | cut -c 13-20 | egrep -v ${keepers_egrep})
+
 # echo the command if there are any to delete
 # command is interactive
 if [ -z "$deleters" ]; then
-    echo "# Nothing to delete!"
+  echo "# Nothing to delete!"
 else
-    echo 'gpg --delete-keys' $deleters
+  echo 'gpg --delete-keys' $deleters
 fi
diff --git a/bin/local-vault-auth b/bin/local-vault-auth
--- a/bin/local-vault-auth
+++ b/bin/local-vault-auth
@@ -1,10 +1,13 @@
 #!/bin/bash
 set -euo pipefail
 
-function require_gotool {
+function require_gotool() {
   toolname=$(basename $1)
-  if ! ( which ${toolname} >/dev/null 2>&1 ); then
-    go version || { echo "${basename} not found and no usable go environment"; exit 1; }
+  if ! (which ${toolname} >/dev/null 2>&1); then
+    go version || {
+      echo "${basename} not found and no usable go environment"
+      exit 1
+    }
     go get -u $1
   fi
 }
@@ -15,7 +18,7 @@ source "${HOME}/.config/vault-user-token"
 source "${HOME}/bin/script_framework.sh"
 
 # Check whether a valid token is available
-( vault token-lookup >/dev/null 2>&1 ) && exit 0
+(vault token-lookup >/dev/null 2>&1) && exit 0
 
 step "Vault is not authenticated, trying to authenticate... "
 
@@ -23,7 +26,10 @@ step "Vault is not authenticated, trying to authenticate... "
 rm -f "${HOME}/.vault-token"
 
 VUT=$(pgrep -f vault-user-token || echo "" | xargs)
-[ -n "$VUT" ] && { step "Killing old vault-user-token processes..."; kill ${VUT}; }
+[ -n "$VUT" ] && {
+  step "Killing old vault-user-token processes..."
+  kill ${VUT}
+}
 
 # Start new vault-user-token daemon
 vault-user-token --full-hostname=false >/dev/null 2>&1 &
@@ -34,11 +40,11 @@ while ! [ -f "${HOME}/.vault-token" ]; do
   # Give the program a moment to get a token
   sleep 0.5
 
-  if ! ( kill -0 $VUT ); then
+  if ! (kill -0 $VUT); then
     fail "vault-user-token exitted, giving up."
   fi
 done
 
-( vault token-lookup >/dev/null 2>&1 ) || fail "Vault authentication failed finally"
+(vault token-lookup >/dev/null 2>&1) || fail "Vault authentication failed finally"
 
 success "Vault token became available and is valid"
diff --git a/bin/resume b/bin/resume
--- a/bin/resume
+++ b/bin/resume
@@ -3,11 +3,11 @@
 source "${HOME}/bin/script_framework.sh"
 
 [ -n "${TMUX}" ] && fail "You are already in tmux!"
-( which tmux 2>/dev/null ) || fail "No tmux found, can't continue"
+(which tmux 2>/dev/null) || fail "No tmux found, can't continue"
 
 tmux-agent
 
-if ! ( tmux list-sessions ); then
+if ! (tmux list-sessions); then
   tmux new-session -d
   tmux split-window -h
 fi
diff --git a/bin/system-audit b/bin/system-audit
--- a/bin/system-audit
+++ b/bin/system-audit
@@ -5,17 +5,18 @@ set -e
 
 BASE_PATH=/tmp/system-audit
 GIT_DIR=/var/local/system-audit
-  
-function collect_hashes {
-  target=$1; shift
+
+function collect_hashes() {
+  target=$1
+  shift
   for dir in $@; do
     if ! [ -e "${dir}" ]; then
-      echo "${dir}" >> ${BASE_PATH}/missing
+      echo "${dir}" >>${BASE_PATH}/missing
       wrap_git add --intent-to-add ${BASE_PATH}/missing
       continue
     fi
 
-    find ${dir} -mindepth 1 \( -type f -or -type l \) -print0 | xargs -0 shasum -a 512 >> ${target}
+    find ${dir} -mindepth 1 \( -type f -or -type l \) -print0 | xargs -0 shasum -a 512 >>${target}
   done
 
   if [ -e ${target} ]; then
@@ -23,7 +24,7 @@ function collect_hashes {
   fi
 }
 
-function wrap_git {
+function wrap_git() {
   git --work-tree=${BASE_PATH} --git-dir=${GIT_DIR} "$@"
   return $?
 }
@@ -44,51 +45,51 @@ fi
 
 case "$1" in
 
-"collect")
-  # Remove old hash-files
-  rm -rf ${BASE_PATH}/*
+  "collect")
+    # Remove old hash-files
+    rm -rf ${BASE_PATH}/*
 
-  # [OSX / Linux] Changing this script will cause a different behaviour
-  # so also this needs to be monitored.
-  collect_hashes ${BASE_PATH}/script          $0
+    # [OSX / Linux] Changing this script will cause a different behaviour
+    # so also this needs to be monitored.
+    collect_hashes ${BASE_PATH}/script $0
 
-  # [OSX only] LaunchAgents and LaunchDaemons can be used to execute
-  # programs on behalf of the user or the root user. They may be used
-  # as attack vectors.
-  collect_hashes ${BASE_PATH}/agents_daemons  /System/Library/LaunchDaemons /Library/LaunchDaemons /System/Library/LaunchAgents /Library/LaunchAgents ~/Library/LaunchAgents
+    # [OSX only] LaunchAgents and LaunchDaemons can be used to execute
+    # programs on behalf of the user or the root user. They may be used
+    # as attack vectors.
+    collect_hashes ${BASE_PATH}/agents_daemons /System/Library/LaunchDaemons /Library/LaunchDaemons /System/Library/LaunchAgents /Library/LaunchAgents ~/Library/LaunchAgents
 
-  # [OSX / Linux ] /etc (or /private/etc on OSX) does contain configuration
-  # for system applications and might be used to change their behaviour.
-  collect_hashes ${BASE_PATH}/etc             /etc /private/etc
+    # [OSX / Linux ] /etc (or /private/etc on OSX) does contain configuration
+    # for system applications and might be used to change their behaviour.
+    collect_hashes ${BASE_PATH}/etc /etc /private/etc
 
-  # [OSX / Linux] Binary folders do contain the executables used by the
-  # system itself. Exchanging them can cause harm to the system or leak
-  # data.
-  collect_hashes ${BASE_PATH}/bin             /usr/bin /usr/local/bin ~/bin
-  ;;
+    # [OSX / Linux] Binary folders do contain the executables used by the
+    # system itself. Exchanging them can cause harm to the system or leak
+    # data.
+    collect_hashes ${BASE_PATH}/bin /usr/bin /usr/local/bin ~/bin
+    ;;
 
-"freeze")
-  wrap_git commit -S -a -m "Status freeze as of $(date)"
-  ;;
+  "freeze")
+    wrap_git commit -S -a -m "Status freeze as of $(date)"
+    ;;
 
-"check")
-  $0 collect
-  $0 diff --exit-code
-  echo "Everything is still in recorded state"
-  ;;
+  "check")
+    $0 collect
+    $0 diff --exit-code
+    echo "Everything is still in recorded state"
+    ;;
 
-"init")
-  if [ $($0 log --pretty=format:'%h [%G?]%d %s (%cr) <%an>' --abbrev-commit | wc -l) -gt 0 ]; then
-    echo "The status was already initialized. Use 'collect' and 'diff' to review the state and 'freeze' to save it"
-    exit 1
-  fi
+  "init")
+    if [ $($0 log --pretty=format:'%h [%G?]%d %s (%cr) <%an>' --abbrev-commit | wc -l) -gt 0 ]; then
+      echo "The status was already initialized. Use 'collect' and 'diff' to review the state and 'freeze' to save it"
+      exit 1
+    fi
 
-  $0 collect
-  $0 freeze
-  ;;
+    $0 collect
+    $0 freeze
+    ;;
 
-*)
-  wrap_git "$@"
-  ;;
+  *)
+    wrap_git "$@"
+    ;;
 
 esac
