Make errors more verbose
Signed-off-by: Knut Ahlers <knut@ahlers.me>

diff --git a/bin/resume b/bin/resume
--- a/bin/resume
+++ b/bin/resume
@@ -1,6 +1,12 @@
 #!/bin/bash
 
-[ -n "${TMUX}" ] && exit 1
+function fail {
+  echo "Error: $@"
+  exit 1
+}
+
+[ -n "${TMUX}" ] && fail "You are already in tmux!"
+( which tmux 2>/dev/null ) || fail "No tmux found, can't continue"
 
 tmux-agent
 
